/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        primary: "#b52330",
        "primary-container": "#ff5a5f",
        "primary-fixed": "#ffdad8",
        "primary-fixed-dim": "#ffb3b0",
        "on-primary": "#ffffff",
        "on-primary-container": "#61000e",
        "on-primary-fixed": "#410007",
        secondary: "#006a62",
        "secondary-container": "#7af7e8",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#00201d",
        background: "#fbf9f8",
        surface: "#fbf9f8",
        "surface-bright": "#fbf9f8",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f5f3f3",
        "surface-container": "#f0eded",
        "surface-container-high": "#eae8e7",
        "surface-container-highest": "#e4e2e2",
        "surface-variant": "#e4e2e2",
        "surface-dim": "#dbd9d9",
        "on-background": "#1b1c1c",
        "on-surface": "#1b1c1c",
        "on-surface-variant": "#5a403f",
        "inverse-surface": "#303030",
        "inverse-on-surface": "#f2f0f0",
        outline: "#8e706f",
        "outline-variant": "#e2bebc",
        tertiary: "#be0a28",
        error: "#ba1a1a",
      },
      fontFamily: {
        sans: ["Inter", "system-ui", "sans-serif"],
        display: ["Plus Jakarta Sans", "Inter", "system-ui", "sans-serif"],
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "0", fontWeight: "800" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "0", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "0", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "28px", letterSpacing: "0" }],
        "body-md": ["16px", { lineHeight: "24px", letterSpacing: "0" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0", fontWeight: "700" }],
      },
      borderRadius: {
        sm: "0.25rem",
        DEFAULT: "0.5rem",
        lg: "0.75rem",
        xl: "1rem",
        "2xl": "1.25rem",
      },
      boxShadow: {
        ambient: "0 12px 40px -18px rgba(19, 27, 46, 0.26)",
        "ambient-soft": "0 8px 32px rgba(19, 27, 46, 0.06)",
        "top-bar": "0 -8px 28px rgba(19, 27, 46, 0.08)",
      },
      spacing: {
        "container-x": "2rem",
        "card-gap": "1.5rem",
      },
    },
  },
  plugins: [],
};
